### PR TITLE
Bible Parser for Bibles in json formats [C#]

### PR DESCRIPTION
**Pull request by olaolumusic**
Hi @Honza,
Thanks for providing us with these priced items, I thought it would be great for me to also share the code written to consummate it. 
This unit test should pass for all the Json versions of the uploaded bible.
I am intending to push them to MongoDB as am not too sure of how it will scale on SQL SERVER given that I would love users to be able to switch translations.
Should there be any need to further add resource, please let me know.
Regards

### CODE REVIEW

**Comment by honza** [comment]
This is awesome! Would you mind moving the file to a `contrib` directory, and giving it a nicer name? Something like `contrib/example.cs`?

**Comment by honza** [comment]
Thanks, perfect. Before I merge: I just realized that my repo doesn't have a license. Are you happy with MIT?

**Comment by olaolumusic** [comment]
Oh sure..!!

**Comment by honza** [comment]
Thanks!

**Pull request merged**
